notifications:
  email:
    on_success: change
language: python
os: linux

services:
  - docker

before_install:
- docker-compose up -d --build

jobs:
  include:
    - stage: "Unit tests"
      name: "3.7"
      branches:
        only:
          - master
      python: "3.7"
      install:
        - pip install -r requirements.txt
      script:
        - python -m unittest test.create_schema_test
        - python -m unittest test.populate_test
    - name: "3.8"
      branches:
        only:
          - master
      python: "3.8"
      install:
        - pip install -r requirements.txt
      script:
        - python -m unittest test.create_schema_test